@startuml
autonumber

Client -> Server: /info
Server -> Client: InfoResponse

Client -> Server: /start
Server -> Client: BuildInfo

Client -> Server: /check frequently
Server -> Client: BuildInfo

Server -> Git: clone
Git -> Server: source

Server -> Server: Build maven
Server -> Server: Zip result

Server -> UploadUrl: upload

Client -> Server: /check
Server -> Client: BuildInfo
@enduml
